import {useEffect,useRef,useState} from 'react';
import {Download,Upload,Trash2,Swords,Square,Plus,Pencil} from 'lucide-react';
import {Button} from './components/ui/button';import {FormationEditor} from './components/FormationEditor';
import {useAppStore} from './store/appStore';import {createExport,downloadExport,parseImport} from './services/transfer';import {toRuntimeFormation} from './runtime/formationAdapter';import {runtimeClient} from './runtime/runtimeClient';
import type {Formation} from './domain/schemas';import type {RuntimeResult} from './runtime/contracts';

type Page='formations'|'battle'|'data';
export default function App(){
 const store=useAppStore(),input=useRef<HTMLInputElement>(null);const [page,setPage]=useState<Page>('formations');const [editing,setEditing]=useState<Formation|'new'|null>(null);const [notice,setNotice]=useState('');const [running,setRunning]=useState(false);const [result,setResult]=useState<RuntimeResult|null>(null);const [allyId,setAllyId]=useState('');const [enemyId,setEnemyId]=useState('');
 useEffect(()=>{void store.load();},[store.load]);useEffect(()=>{if(!allyId)setAllyId(store.formations.find(f=>f.kind==='ally')?.id||'');if(!enemyId)setEnemyId(store.formations.find(f=>f.kind==='enemy')?.id||'');},[store.formations,allyId,enemyId]);
 const ally=store.formations.find(f=>f.id===allyId),enemy=store.formations.find(f=>f.id===enemyId);
 async function importFile(file?:File){if(!file)return;try{const value=parseImport(await file.text());await store.replaceAll(value.formations);setNotice(`${value.formations.length}件を読み込みました`);}catch{setNotice('形式が正しくないため読み込めません');}}
 async function calculate(){if(!ally||!enemy)return;setRunning(true);setNotice('b223 runtimeを起動中…');try{const value=await runtimeClient.calculate({candidate:toRuntimeFormation(ally),target:enemy.id,target_spec:toRuntimeFormation(enemy),trials:10,blocks:1,seed:1326230000,include_detail:true});if(typeof value.win_rate!=='number')throw new Error('勝率が返されませんでした');setResult(value);await store.saveBattleResult({id:crypto.randomUUID(),allyId:ally.id,enemyId:enemy.id,createdAt:new Date().toISOString(),status:'completed',winRate:value.win_rate,hpDiff:typeof value.hp_diff==='number'?value.hp_diff:null,trials:10,blocks:1,runtime:value.runtime,payload:value});setNotice('計算が完了しました');}catch(e){setNotice(e instanceof Error?e.message:'計算に失敗しました');}finally{setRunning(false);}}
 if(editing)return <Shell><FormationEditor initial={editing==='new'?undefined:editing} onCancel={()=>setEditing(null)} onSave={async value=>{await store.save(value);setEditing(null);setNotice('編成を保存しました');}}/></Shell>;
 return <Shell><main className="space-y-4 pb-24">{notice&&<p role="status" className="rounded-xl bg-amber-950 p-3 text-sm text-amber-300">{notice}</p>}
 {page==='formations'&&<><div className="flex items-center justify-between"><h2 className="text-xl font-bold">編成</h2><Button onClick={()=>setEditing('new')}><Plus className="mr-2 size-4"/>新規</Button></div>{store.loading&&<p>読込中...</p>}{!store.loading&&!store.formations.length&&<p className="rounded-2xl border border-slate-700 bg-slate-900 py-12 text-center text-slate-500">編成を登録してください</p>}{store.formations.map(f=><article key={f.id} className="flex items-center justify-between rounded-2xl border border-slate-700 bg-slate-900 p-4"><div><strong>{f.name}</strong><p className="text-xs text-slate-400">{f.kind==='enemy'?'敵軍':'自軍'}・{f.troopType} Lv{f.troopLevel}・兵力{f.troops}</p></div><div className="flex gap-2"><Button aria-label={`${f.name}を編集`} variant="secondary" onClick={()=>setEditing(f)}><Pencil className="size-4"/></Button><Button aria-label={`${f.name}を削除`} variant="danger" onClick={()=>void store.remove(f.id)}><Trash2 className="size-4"/></Button></div></article>)}</>}
 {page==='battle'&&<><h2 className="text-xl font-bold">対戦</h2><section className="space-y-3 rounded-2xl border border-amber-800 bg-slate-900 p-4"><label className="block text-sm text-slate-400">自軍<select aria-label="自軍" className="mt-1 w-full rounded-lg bg-slate-950 p-3" value={allyId} onChange={e=>setAllyId(e.target.value)}><option value="">選択</option>{store.formations.filter(f=>f.kind==='ally').map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="block text-sm text-slate-400">敵軍<select aria-label="敵軍" className="mt-1 w-full rounded-lg bg-slate-950 p-3" value={enemyId} onChange={e=>setEnemyId(e.target.value)}><option value="">選択</option>{store.formations.filter(f=>f.kind==='enemy').map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>{running?<Button variant="danger" className="w-full" onClick={()=>{runtimeClient.cancel();setRunning(false);setNotice('計算を中止しました');}}><Square className="mr-2 size-4"/>中止</Button>:<Button className="w-full" disabled={!ally||!enemy} onClick={()=>void calculate()}><Swords className="mr-2 size-4"/>10×1で計算</Button>}{result&&<ResultCard result={result}/>}</section><h3 className="font-bold">計算履歴</h3>{store.battleResults.slice(0,10).map(x=><article key={x.id} className="rounded-xl bg-slate-900 p-3"><strong>{(x.winRate*100).toFixed(1)}%</strong><span className="ml-3 text-xs text-slate-400">HP差 {x.hpDiff?.toFixed(1)??'—'}・{new Date(x.createdAt).toLocaleString('ja-JP')}</span></article>)}</>}
 {page==='data'&&<><h2 className="text-xl font-bold">データ</h2><section className="rounded-2xl border border-slate-700 bg-slate-900 p-4"><div className="grid grid-cols-2 gap-3"><Button onClick={()=>downloadExport(createExport(store.formations))} disabled={!store.formations.length}><Download className="mr-2 size-4"/>Export</Button><Button variant="secondary" onClick={()=>input.current?.click()}><Upload className="mr-2 size-4"/>Import</Button></div><input ref={input} className="hidden" type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/></section></>}
 </main><nav className="fixed inset-x-0 bottom-0 z-10 mx-auto grid max-w-3xl grid-cols-3 border-t border-slate-700 bg-slate-950/95 p-2 safe-bottom">{([['formations','編成'],['battle','対戦'],['data','データ']] as const).map(([id,label])=><button key={id} className={`min-h-12 rounded-lg ${page===id?'bg-amber-500 text-slate-950':'text-slate-400'}`} onClick={()=>setPage(id)}>{label}</button>)}</nav></Shell>;
}
function Shell({children}:{children:React.ReactNode}){return <div className="mx-auto min-h-screen max-w-3xl px-4 safe-top safe-bottom"><header className="py-5"><p className="text-xs tracking-[.3em] text-amber-400">SHINSEN TOOLKIT</p><h1 className="text-3xl font-black">NOBU Companion</h1><p className="mt-2 text-sm text-slate-400">b223 canonical runtime</p></header>{children}</div>}
function ResultCard({result}:{result:RuntimeResult}){return <div className="rounded-xl bg-slate-950 p-4"><p className="text-sm text-slate-400">実勝率</p><p className="text-3xl font-black text-amber-400">{typeof result.win_rate==='number'?`${(result.win_rate*100).toFixed(1)}%`:'—'}</p><p className="text-sm text-slate-400">HP差 {typeof result.hp_diff==='number'?result.hp_diff.toFixed(1):'—'}</p><p className="mt-2 text-xs text-slate-500">{result.runtime} / {result.version}</p></div>}
